### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by akatsuki** [slipcor/TreeAssist#11]
The pom.xml doesn't work at maven...

**Comment by slipcor** [comment]
It works for me. Which error do you get?

**Comment by akatsuki** [comment]
This is logs.

akatsuki$ mvn install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for me.itsatacoshop247.TreeAssist:TreeAssist:jar:5.10-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for me.botsko:prism:jar should not point at files within the project directory, ${project.basedir}/lib/prism-2.0.4.jar will be unresolvable by dependent projects @ line 42, column 25
[WARNING] 'dependencies.dependency.systemPath' for de.diddiz:logblock:jar should not point at files within the project directory, ${project.basedir}/lib/LogBlock1.94.jar will be unresolvable by dependent projects @ line 50, column 25
[WARNING] 'dependencies.dependency.systemPath' for de.diddiz:questioner:jar should not point at files within the project directory, ${project.basedir}/lib/LogBlockQuestioner.jar will be unresolvable by dependent projects @ line 58, column 25
[WARNING] 'dependencies.dependency.systemPath' for net.coreprotect:CoreProtect:jar should not point at files within the project directory, ${project.basedir}/lib/CoreProtect_2.12.0.jar will be unresolvable by dependent projects @ line 66, column 25
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building TreeAssist 5.10-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/bukkit/1.9.2-R0.1-SNAPSHOT/maven-metadata.xml
Downloading: https://ci.drtshock.net/plugin/repository/everything/org/bukkit/bukkit/1.9.2-R0.1-SNAPSHOT/maven-metadata.xml
Downloaded: https://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/bukkit/1.9.2-R0.1-SNAPSHOT/maven-metadata.xml (2 KB at 0.6 KB/sec)
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.pom
Downloading: https://ci.drtshock.net/plugin/repository/everything/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.pom
Downloading: https://repo.maven.apache.org/maven2/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.pom
[WARNING] The POM for com.gmail.nossr50.mcMMO:mcMMO:jar:1.5.03 is missing, no dependency information available
Downloading: https://hub.spigotmc.org/nexus/content/groups/public/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.jar
Downloading: https://ci.drtshock.net/plugin/repository/everything/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.jar
Downloading: https://repo.maven.apache.org/maven2/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.474 s
[INFO] Finished at: 2017-02-22T12:17:05+09:00
[INFO] Final Memory: 8M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project TreeAssist: Could not resolve dependencies for project me.itsatacoshop247.TreeAssist:TreeAssist:jar:5.10-SNAPSHOT: Could not find artifact com.gmail.nossr50.mcMMO:mcMMO:jar:1.5.03 in spigot-repo (https://hub.spigotmc.org/nexus/content/groups/public/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by slipcor** [comment]
Okay, seems like the mcMMO repo has changed or they removed the version I specified. I will look into this later :)




  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/slipcor/TreeAssist","title":"slipcor/TreeAssist","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/slipcor/TreeAssist"}},"updates":{"snippets":[{"icon":"PERSON","message":"@akatsuki in #11: This is logs.\r\n\r\nakatsuki$ mvn install\r\n[INFO] Scanning for projects...\r\n[WARNING] \r\n[WARNING] Some problems were encountered while building the effective model for me.itsatacoshop247.TreeAssist:TreeAssist:jar:5.10-SNAPSHOT\r\n[WARNING] 'dependencies.dependency.systemPath' for me.botsko:prism:jar should not point at files within the project directory, ${project.basedir}/lib/prism-2.0.4.jar will be unresolvable by dependent projects @ line 42, column 25\r\n[WARNING] 'dependencies.dependency.systemPath' for de.diddiz:logblock:jar should not point at files within the project directory, ${project.basedir}/lib/LogBlock1.94.jar will be unresolvable by dependent projects @ line 50, column 25\r\n[WARNING] 'dependencies.dependency.systemPath' for de.diddiz:questioner:jar should not point at files within the project directory, ${project.basedir}/lib/LogBlockQuestioner.jar will be unresolvable by dependent projects @ line 58, column 25\r\n[WARNING] 'dependencies.dependency.systemPath' for net.coreprotect:CoreProtect:jar should not point at files within the project directory, ${project.basedir}/lib/CoreProtect_2.12.0.jar will be unresolvable by dependent projects @ line 66, column 25\r\n[WARNING] \r\n[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.\r\n[WARNING] \r\n[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.\r\n[WARNING] \r\n[INFO]                                                                         \r\n[INFO] ------------------------------------------------------------------------\r\n[INFO] Building TreeAssist 5.10-SNAPSHOT\r\n[INFO] ------------------------------------------------------------------------\r\nDownloading: https://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/bukkit/1.9.2-R0.1-SNAPSHOT/maven-metadata.xml\r\nDownloading: https://ci.drtshock.net/plugin/repository/everything/org/bukkit/bukkit/1.9.2-R0.1-SNAPSHOT/maven-metadata.xml\r\nDownloaded: https://hub.spigotmc.org/nexus/content/groups/public/org/bukkit/bukkit/1.9.2-R0.1-SNAPSHOT/maven-metadata.xml (2 KB at 0.6 KB/sec)\r\nDownloading: https://hub.spigotmc.org/nexus/content/groups/public/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.pom\r\nDownloading: https://ci.drtshock.net/plugin/repository/everything/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.pom\r\nDownloading: https://repo.maven.apache.org/maven2/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.pom\r\n[WARNING] The POM for com.gmail.nossr50.mcMMO:mcMMO:jar:1.5.03 is missing, no dependency information available\r\nDownloading: https://hub.spigotmc.org/nexus/content/groups/public/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.jar\r\nDownloading: https://ci.drtshock.net/plugin/repository/everything/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.jar\r\nDownloading: https://repo.maven.apache.org/maven2/com/gmail/nossr50/mcMMO/mcMMO/1.5.03/mcMMO-1.5.03.jar\r\n[INFO] ------------------------------------------------------------------------\r\n[INFO] BUILD FAILURE\r\n[INFO] ------------------------------------------------------------------------\r\n[INFO] Total time: 7.474 s\r\n[INFO] Finished at: 2017-02-22T12:17:05+09:00\r\n[INFO] Final Memory: 8M/245M\r\n[INFO] ------------------------------------------------------------------------\r\n[ERROR] Failed to execute goal on project TreeAssist: Could not resolve dependencies for project me.itsatacoshop247.TreeAssist:TreeAssist:jar:5.10-SNAPSHOT: Could not find artifact com.gmail.nossr50.mcMMO:mcMMO:jar:1.5.03 in spigot-repo (https://hub.spigotmc.org/nexus/content/groups/public/) -\u003e [Help 1]\r\n[ERROR] \r\n[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.\r\n[ERROR] Re-run Maven using the -X switch to enable full debug logging.\r\n[ERROR] \r\n[ERROR] For more information about the errors and possible solutions, please read the following articles:\r\n[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException"}],"action":{"name":"View Issue","url":"https://github.com/slipcor/TreeAssist/issues/11#issuecomment-281557327"}}}

**Comment by akatsuki** [comment]
Thank you!
I'll wait for your update!

**Comment by slipcor** [comment]
Alright. for now I added their latest release version as fixed system dependency. You need to download it:

https://github.com/slipcor/TreeAssist/tree/master/lib

If you have a fork locally you should be able to pull, or you can just download the zip again :)

please verify! I still have my local stuff working but it might be because of caching :O

**Comment by akatsuki** [comment]
GREAT JOB!
It perfectly works for me!
Thanks a lot!

**Comment by akatsuki** [comment]
It perfectly works for me!
Thank you!
