### ISSUE TITLE
1.13 update? Not supporting lib from another dev active

### ISSUE THREAD

**Issue by TNTUP** [slipcor/TreeAssist#24]
Just dropping this into this repo, the .52 one does not work with 1.13-pre7's and the latest build from another dev requires a lib plugin which I don't support so I'm stuck to 1.12.2 forever :(

**Comment by pop4959** [comment]
I made a fork of this project that supports 1.13. You can find the repository / download (under releases) on my profile. Perhaps I can get it merged into this one with the help of @slipcor if he is still planning to update this project.

**Comment by TNTUP** [comment]
You're a life saver! Gonna test it out and if case of bugs ill report them either here or somwhere

**Comment by slipcor** [comment]
@pop4959 I have read through your commits, and they look solid. Especially the way that you replaced the checks with a Utils function really tickles my OCD in a nice way :)

I will think about what to do with this. I know that updating this over here on github is not the issue... but releasing this would feel weird because I technically gave the plugin away, and have only the opinion of 2 people so far that there is an issue with that.

**Comment by slipcor** [comment]
I am closing this, assuming it is fixed now in the latest version thanks to @pop4959 :)
