### ISSUE TITLE
[Bug] Saplings, Sapling allways just OakSpalings...

### ISSUE THREAD

**Issue by CloudeLecaw** [slipcor/TreeAssist#25]
Plan a tree (no oak, this would not make sense for this test)

![image](https://user-images.githubusercontent.com/12080017/43208082-d8d1e3f0-9029-11e8-8a30-ef00b2e4dfe5.png)

cut it down
![image](https://user-images.githubusercontent.com/12080017/43208121-f70f0f78-9029-11e8-8f9d-6e494bf2f724.png)

wait a few Secounds
![image](https://user-images.githubusercontent.com/12080017/43208143-057c5aca-902a-11e8-9f0d-28ea5609053d.png)

Tested with: latest TreeAssists from Jenkins + Latest AcronisX from Jenkins + Spigot 1.13 (1 day old)

**Comment by pop4959** [comment]
I've fixed this bug in an update for this plugin that I made for 1.13. You can find the repository / download (under releases) on my profile.

**Comment by CloudeLecaw** [comment]
im confued now
 your versions is marked as v6.0.7 
and the spigot Version is marked as  TreeAssist 5.13.1

so are there two Versions of TreeAssist now? :3

**Comment by pop4959** [comment]
@CloudeLecaw I just saw that you mentioned Arconix. You might be using Songoda's version of TreeAssist. The repository for that is located [here](https://github.com/Songoda/TreeAssist). This repository is for the original version of TreeAssist by slipcor, which I have forked.

They are both similar, because Songoda's version is also forked from this. However, the difference is as follows:

- This plugin uses the original tree felling animation.
- This plugin does not require an additional library like Arconix to run on your server.
- The bug you mentioned is present in this repository (TreeAssist 5.11.52), but not in my forked version (6.0.7).

Keep in mind that I decided to bump the version number due to the plugin now natively supporting 1.13, with no backwards compatibility to 1.12 and prior. The 5.x branch will work on versions prior to 1.13.

I hope that clarifies any confusion :)

**Comment by CloudeLecaw** [comment]
hm the Problem may for the normal owner like me is. that the link Shows me some…"Things"... but no jarfile that an owner could download.

![image](https://user-images.githubusercontent.com/12080017/43387860-ddcbf0fa-93e7-11e8-836a-dd3ca00841f0.png)

**Comment by pop4959** [comment]
Again, that is not the version on this repository. If you want support for Songoda's version of TreeAssist, you need to post an issue on her repository.

If you want a download to an updated version of this TreeAssist, a jarfile can be found [HERE](https://github.com/pop4959/TreeAssist/releases)

**Comment by CloudeLecaw** [comment]
thank you :-D
i did not know that someone took a fork of the old Version :-)
Yours s one was not published on spigot or bukkit or somewhere else Right? just here…
so Thank you for sharing the link with me <3


personaly for me:
- i dont use the new treefall Animation of the other TreeAssist. i tested it but disabled it because it was not like i wanted or thought of it. Also this made often Problems with the bigger trees.
- good to know that this version can live without the Acronix. i just was using it because of this one plugin. normaly i dont like it if just one Plugin i use needs a whole libary for it. But i can understand devs that does it if they have more Plugins usings the libary.
- good to know that the bug is fixed in your Version :-)

**Comment by slipcor** [comment]
I am closing this, assuming it is fixed now in the latest version thanks to @pop4959 :)
