### ISSUE TITLE
Could TreeAssist be lagging the server?

### ISSUE THREAD

**Issue by Leonardo-Fiori** [slipcor/TreeAssist#39]
Check this timings report: https://timings.aikar.co/?id=9a54aa99688d487086719045151eac97#plugins

![image](https://user-images.githubusercontent.com/25549272/73581228-c20b8f80-4488-11ea-8cfb-245dd4bd2895.png)

Could it be Treeassist? See plugins tab. It's marked as red. I am not sure because i am not a good timings reader :)

**Comment by slipcor** [comment]
same, I think most of the time these numbers are either displayed or sorted weirdly.

one thing you can do is use another plugin for the block list, for example core protect or maybe another compatible rollback plugin which would use database lookups instead of a separate block list (which can get real big :) )

how much data does the world folder contain in the /plugins/TreeAssist contain? Maybe you could use the purge command to get rid of some entries?

/treeassist purge 30

this should get rid of all blocks placed 30 days ago -- technically you might consider the possibility to disable the block list, you can do that by setting "Ignore User Placed Blocks" to true.

This is "one more layer" of making sure that user placed trees are not automatically destroyed, it is your call if you want to try :D

**Comment by slipcor** [comment]
I actually have an idea on how to tweak the saving mechanism. We moved from "saving the related file every time someone breaks a block" to "saving ALL FILES every 1200 ticks"

how about we change this to "saving changed files every 1200 ticks" :D this should reduce the load a bunch. Especially if noone is on the server this will not constantly rewrite all files. Should be ready for testing in a few hours

**Comment by slipcor** [comment]
Can you test this build? This should lag A LOT LESS :D

https://ci2.craftyn.com/job/TreeAssist/lastSuccessfulBuild/artifact/target/TreeAssist.jar

**Comment by Leonardo-Fiori** [comment]
Tested! And it looks cool :P look, the plugin is not marked in red. But the server is still lagging for other reasons i guess hahah
https://timings.aikar.co/?id=99e89c33e1df4cb684f7aabf0e0721a5#plugins

**Comment by slipcor** [comment]
Thanks for reporting back. I will be waiting for a week or so in case there is an issue somewhere that you might report, then I will release it :)

thanks for testing!

yeah minecraft has been buggy especially in 1.14, right? maybe one day they will fix it :/
