### ISSUE TITLE
Inefficient Command Handling

### ISSUE THREAD

**Issue by aikar** [slipcor/TreeAssist#4]
while not as major as #3, commands are using a list instead of a map for command registry

https://github.com/slipcor/TreeAssist/blob/master/src/me/itsatacoshop247/TreeAssist/TreeAssist.java#L120

This should be changed to a map, where you register the command object twice into the map, once for main, and once for short.

Then your command handler will be AbstractCommand command = commands.get(args[0].toLowerCase());

**Comment by slipcor** [comment]
Thanks for the feedback! 
I will try to implement the fixes you proposed, if only because I trust your judgement blindly.
Especially with issue #3 I was lost long ago but did not dare to try a solution like you proposed. Firstly because it was changing a running a system and because I did expect it to break or be unreliable.

**Comment by slipcor** [comment]
okay, but how do I then generate the help string to tell people which commands they have? I have to keep a general list anyways :/ whatever, if the command is valid, it will be quicker soon [tm]
