### ISSUE TITLE
TreeAssist seems to disregard sneak setting in config

### ISSUE THREAD

**Issue by OverlordFreddo** [slipcor/TreeAssist#40]
I would first like to point out that the help link doesn't work due to changes with Bukkit dev.

Secondly, the plugin appears to chop the trees down forcefully regardless of sneaking or not.  I would like for players to 'fell trees' **only** while sneaking.  I set it this way due to the issue of the tree coming down regardless of sneak.

Config on pastebin: https://pastebin.com/Mfpzutbf

**Comment by OverlordFreddo** [comment]
Current config settings: https://pastebin.com/nbvKJWhZ

Expected: Trees destroyed **only** while sneaking.
Actual: Trees get destroyed regardless of setting.

**Comment by slipcor** [comment]
I will get to you shortly. In case I can not reproduce this - and I assume that will be the case because I tested this in the last version because of a bug report :) - are you sure you properly reloaded the plugin / restarted the server for the changes in the config to take effect?

If so, please do the following:

/treeassist debug all

sneak and hit a tree

/treeassist debug off

check the folder .../plugins/treeassist/debug and please upload the contents here. I will have a look at them to see what exactly is happening on your server.

**Comment by slipcor** [comment]
Okay I was able to reproduce this with your config. Here is what happens:

* you set ```Automatic Tree Destruction.Forced Removal``` to true
* the plugin checks for ```Main.Initial Delay``` which you set to false, so the forced removal automatically happens - set this to ```true``` and then the value you set in ```Automatic Tree Destruction.Initial Delay (seconds)``` will be used for this forced removal

You have two ways of fixing this:

1) disable the forced removal
2) set the delay to true and set a number of seconds to wait until that cleanup happens.

I think I need to rework the ordering of some of the config settings, they are all over the place but they are only related to the automatic removal, not to the tree cutting that happens if the player does sneak, in your case.

If you have any feedback, I'd appreciate it!

**Comment by OverlordFreddo** [comment]
Apologies, I planned to get to this tonight but didn't sleep a wink last night and passed out after work.  I will send you the debug information when I'm not sleep deprived anymore.

What I was expecting to happen/what I wanted to happen:
Chopping _without sneaking_ would chop the one log (vanilla behaviour)
Chopping _while sneaking_ would chop down the tree and apply the fast leaf decay.

**Comment by slipcor** [comment]
Yes, in order for this to happen you need to either disable the forced remove (this removes valid trees that have been not completely cut, which any tree that you are cutting and not fully removing qualifies) - or you have to activate and increase the initial delay which is the delay before the forced cleanup removal kicks in :)

**Comment by OverlordFreddo** [comment]
Are you saying that the person has to chop down the entire tree themselves before the plugin would kick in and do anything?

**Comment by slipcor** [comment]
yes, the latter, the delay needs to be activated and increased :) 60 seconds? 300 seconds? then if people get bored of cleaning the tree, the plugin removes remaining tree blocks after 5 minutes

**Comment by OverlordFreddo** [comment]
I was under the impression that this plugin would 'fell' trees more instantly than that.  Something akin to the Treefeller ability in mcMMO or Veinminer.

**Comment by slipcor** [comment]
well yes, it does that when you do sneak, is that not the whole point of what you want? if you sneak it goes down instantly, and if you do not sneak, you activated the cleanup later --- if you do not want this cleanup, disable it and you will only have either sneak-autoremove (instant!) or people manually falling trees with no cleanup

**Comment by slipcor** [comment]
set ```Automatic Tree Destruction.Forced Removal``` to false to disable the cleanup, and I believe you have what you want

**Comment by OverlordFreddo** [comment]
I will try this and report back.  If it happens how you say, it was probably just me misinterpreting the config.

**Comment by slipcor** [comment]
yeah, I will try to update the config with proper order that reflects the scope of its actions, and in-line- comments :)

**Comment by OverlordFreddo** [comment]
Okay so the first time I attempted to debug, it created the folder and file.  When I attempted to do it again, it didn't work - the log did not update and a new one was not created.  So I deleted the folder and the log and tried again - no log or folder generated.

I also do not get a response when I do `/ta debug off` but I do when I do `/ta debug all`

Here is the output from *sneaking* and chopping a tree:
`20.03.17 01:49:24 [INFO] 957 calculating Location{world=CraftWorld{name=115},x=2097.0,y=64.0,z=778.0,pitch=0.0,yaw=0.0}
20.03.17 01:49:24 [INFO] 958 BlockBreak!
20.03.17 01:49:24 [INFO] 958 legacy block
20.03.17 01:49:24 [INFO] 959 OAK
20.03.17 01:49:24 [INFO] 965 placed blocks. Removing!
`

**Comment by OverlordFreddo** [comment]
Here is the output from _not sneaking_ and chopping a tree:
`20.03.17 01:53:52 [INFO] 832 calculating ``Location{world=CraftWorld{name=115},x=2092.0,y=64.0,z=783.0,pitch=0.0,yaw=0.0}`
`20.03.17 01:53:52 [INFO] 833 BlockBreak!`
`20.03.17 01:53:52 [INFO] 833 legacy block`
`20.03.17 01:53:52 [INFO] 833 OAK`
`20.03.17 01:53:52 [INFO] 836 placed blocks. Removing!`

**Comment by slipcor** [comment]
did you try to break a tree of which you placed the wood block back to fall the same tree?

if yes, the plugin prevents player-placed-blocks to count as valid trees (that could be removed automatically) - if you try a freshly spawned tree, it should work as intended.

To disable the "placed blocks" check, set ```Ignore User Placed Blocks: false``` to true

Otherwise we have a problem with the placed blocks implementation with CoreProtect ... I'd have to download the plugin to debug it... but I hope that you have been breaking and repairing trees :)

**Comment by OverlordFreddo** [comment]
They were both freshly grown trees - I placed saplings and allowed them to grow.  There was no 'tree surgery' involved. (haha)

**Comment by slipcor** [comment]
Okay. Thanks for your time. I will have to setup testing with CoreProtect. If you want it to work right now, you can set the config I said in my last post to "true" so it will ignore placed blocks, for some reason this check is being returned as "a player placed this block" even though it ... could be that you placed a sapling there or somehow a tree growing normaly by spawning counts as that. I have to look into that.

**Comment by slipcor** [comment]
I tried something, maybe it works for you? http://pa.slipcor.net/TreeAssist.jar

**Comment by slipcor** [comment]
It will probably not work with coreprotect (right now).

I have to look into how to make this work properly --- when you turned the sapling into a tree, the plugin registered this as "placement: wood block" - I will try to look into how to determine whether you did this by actually placing or by growing.

I will keep you posted!

**Comment by slipcor** [comment]
I think you should be fine enabling the config setting I mentioned. CoreProtect manages reverting of bad things happening. So this ```User Placed Blocks``` thing exists for the case where someone tries to use the tree feller to destroy someone's home. TreeAssist will log what happened and will log it under the name of the player who did it, so reverting what the player did will revert the damage!

In order to double check if a log is placed by a player placing it literally or by a tree growing because the player grew it - I would have to maintain a list of all blocks that were part in all trees being grown - or of all blocks being placed - There is no distinction in the data I receive (that I could find).

And maintaining such a list sort of defeats the purpose of using CoreProtect instead of that flatfile implementation ;) Just ignore the placed blocks...
