### ISSUE TITLE
Multiple new issues

### ISSUE THREAD

**Issue by VL4DST3R** [slipcor/TreeAssist#61]
I found a few more issues while playing after your latest update, namely:

1. tall jungle trees plant oak saplings instead of jungle when cut
![2020-09-29_19 18 28](https://user-images.githubusercontent.com/32654378/94701193-05363f00-0345-11eb-95cc-dec0adae18e4.jpg)

2. Trees sometimes lose their top part of the leaves (not limited to jungle trees like previous issues) This is caused by leaves from other cut trees "leeching off" the falling effect to nearby trees, basically ignoring the fact those are still attached to an intact tree log.
![2020-09-30_17 51 02](https://user-images.githubusercontent.com/32654378/94701673-95748400-0345-11eb-8a04-e77f2f5ba26f.jpg)

3. When you cut multiple intersecting trees, not all leaves decay properly, leaving some that decay at vanilla speeds
![2020-09-30_17 44 15](https://user-images.githubusercontent.com/32654378/94701182-023b4e80-0345-11eb-81d0-4ba0f6596e3c.jpg)

4. some trees don't actually fall, as intended by the plugin. im guessing it is because it detects it was previously cut by a player in the same spot and thinks it's not supposed to remove it?

5. Finally, not really an issue as much as a request: the replanting of saplings takes quite a while, not knowing if it will actually plant a new sapling by itself or not (sometimes it doesn't, not sure if it's intended or not). Could it be sped up to place the sapling immediately after breaking the tree?

**Comment by slipcor** [comment]
1) While debugging 2) I could reproduce this and I think I will just remove the definition of the small bush. This messed up definition just breaks the jungle trees

2) I fixed this and I have to push this ASAP, I had a typo in a check for whether leaves are without trees :(

3) There might not be a way to fix this because this bug specifically was caused by making the "is the tree leaf alone" check more leaning towards "no", to prevent shrubbery from getting obliterated... I can not do much more about that. because of how Jungle bushes are OAK leaves and JUNGLE log, I cannot even compare both types because they are not always the same, apparently :/

4) This should only happen during the "cleanup" phase, when basically the first cleanup cuts into the second tree... so if you have a cleanup delay, tell this to your players so they do not set up farms that are too fast for this, or so that they do not replenish the trees too quickly

5) Again, this is working against 4) - Sapling replanting is waiting for the cleanup to happen. if I replace the sapling before the cleanup is done, the tree can grow again and the cleanup then removes leaves or even logs of the new tree :/

**Comment by VL4DST3R** [comment]
3. >     I can not do much more about that. because of how Jungle bushes are OAK leaves and JUNGLE log, I cannot even compare both types because they are not always the same, apparently :/

But do you actually need to check if the leaves type **match** the log they are next to? Sounds like you can ignore this safely, or am i missing something?

4. What exactly do you mean by "cleanup delay"? is it an option i can configure for the plugin? I haven't knowingly set anything like that. As to telling players to be mindful and follow ANY kind of special rules, let's be real: as you can probably imagine, i can't realistically expect them to keep stuff like this in mind, especially for newer players, so i have to set it up so that's bug-free by the time they get to use it :)

5. Understandable. But here is a question. I noticed the leaves decay in random groups, compared to the logs themselves which all start falling instantly. Is this a limitation of how you can make the leaves decay? If you can make them all fall at once wouldn't that help sped up this whole "cleaup" stage?

**Comment by VL4DST3R** [comment]
I should also take a moment and thank you for all the support you offer for your plugin and the help with my queries. Really appreciate it man 👍

**Comment by slipcor** [comment]
It is my pleasure 👍 

So first off, I am ignoring this as of now (after the fix) so as soon as there is a log nearby it will be considered belonging to a tree :)

It's just that I dislike this solution because it does not really 100% safely detect the trees but just detects all logs...

4) yes you can configure this, look up for Cleanup, it is what the plugin does when it removes remnants of the trees people started chopping :)

5) no it is something that tries to "continue finding more leaves" when it finds a leaf that is far away from a log block. so before (in the version you reported) it would just plunge through the forest and clear all tops and all jungle brushes above the log, now it should stop in a radius around logs.

The difference you are asking is that the tree destruction is triggered by someone hitting a log block, and then it calculates from the inside out, but the leaf decay starts as soon as minecraft detects a leaf block too far away to be "prevented from decaying" and then my plugin finds more next to it to remove, and then it continues from there :)

About the point of "making them drop at once", yes you can do that by setting the Delays to -1 and then every destruction / cleanup is instant :)

**Comment by VL4DST3R** [comment]
Awesome, Thank you! Will try the delay and cleanup settings you mentioned first time tomorrow when i wake up!


> It's just that I dislike this solution because it does not really 100% safely detect the trees but just detects all logs...
Isn't this how vanilla (used) to keep player-placed leaves from despawning as well?

In the past you had to actually place logs to keep them from disappearing, compared to now when they can be placed by themselves, anywhere, without decay.

Considering the only place where this could be an issue is near a player-made structure that uses logs in it, it will rarely be a problem out in the wild and in farms, places where you usualy cut most of your trees. Yes, at the end of the day it's a tradeoff between the two. Maybe add both methods and let the user decide which one to use?

> The difference you are asking is that the tree destruction is triggered by someone hitting a log block, and then it calculates from the inside out, but the leaf decay starts as soon as minecraft detects a leaf block too far away to be "prevented from decaying" and then my plugin finds more next to it to remove, and then it continues from there :)

So wait, which issue exactly is the one you are describing here? Ah, maybe I'm getting tired and we should resume this tomorrow XD


Finally also, could you maybe update your spigot page with the latest build and such? Just for everyone's convenience :P

**Comment by slipcor** [comment]
Yeaah I did upload this build and I will think about what you said and think about adding a config option :)

Sorry if I was stumbling over my words, I will try to do all the things tomorrow, when I am sober :D

Thank you for your feedback and I will try to make this right so it makes sense for you, if it is possible to do so
