### ISSUE TITLE
Re: last update post

### ISSUE THREAD

**Issue by VL4DST3R** [slipcor/TreeAssist#63]
Hey! It's me again! Happy holidays btw!

> I would like to find out if some features are used at ALL any more, so I added some more detailed stats. Maybe we can remove some things that one person requested ages ago and that might cause more trouble than it does good?

What exactly you have in mind to remove? I have, in fact, changed quite a few things in the config, mainly enabling the absolutely gorgeous tree cutting/falling animation you made -which is quite unique- and a few other values i can't remember off the top of my head. I'd hate to see stuff like this go! As far as i know your plugin now works without any issues, so why fix something that ain't broken? :/

**Comment by slipcor** [comment]
Hey! Happy holidays to you too!

Nothing comes to mind at the moment, but let us just say for the sake of argument that out of 1000 servers, actually 0 people use the "restrict world" feature, but internally I constantly bump into this because I have to double check the setting here and there...

I do not know if I ever will actuall go through with this, but it would help anyway just to know what percentage is using what in order to have an idea of what could be causing bugs, for example I learned that among the 50 first servers, there was one server that activated the fancy blocks node, but not the falling blocks node - I now plan to add a warning for this because if I remember correctly it will not even make anything fancy because the falling blocks are a prerequisite for fancy blocks :)

And in general I will only remove or change anything if I feel that this is making it a lot easier for me in the long run, or less buggy. As you said, the current version is pretty stable as it is, so I do not have a candidate for that yet :)

**Comment by VL4DST3R** [comment]
If i can suggest something, do consider adding `#comments` for every option inside your `.yml` configs so people (like me) can better understand what your plugin actually has to offer. I configured mine initially a bit "in the blind" hoping stuff will turn out as i wanted it to, and it did, but it wasn't really a smooth experience, i just got lucky.

**Comment by slipcor** [comment]
well in your actual configs there should be comments! practically every line should have a comment in there. If that does not work for you then I have to look into why :)

**Comment by VL4DST3R** [comment]
My configs are a few versions old, maybe that's why? I only have a few comments at best.

```# === [ General Settings ] ===
General:
  # Language file to load. Does not need YML extension!
  Language: lang_en
  Toggle Default: true
  Use Permissions: false
# === [ Command Settings ] ===
Commands:
  Force Break:
    Default Radius: 10
    Max Radius: 30
  Force Grow:
    Default Radius: 10
    Max Radius: 30
  No Replant:
    Cooldown Time: 30
# === [ Automatic Destruction Settings ] ===
Destruction:
  Falling Blocks: true
  Falling Blocks Fancy: true
  Fast Leaf Decay: true
  Only Above: false
Placed Blocks:
  Active: true
  Plugin Name: CoreProtect
  Lookup Time: 86400
# === [ Plugin Integration Settings ] ===
Plugins:
  # Count broken blocks towards the TreeFeller ability
  mcMMO: false
  # Count broken blocks towards Jobs jobs that fit
  Jobs: false
  # Allow to set up regions with WorldGuard to prevent destruction with 'treeassist-autochop' and sapling replacement with 'treeassist-replant'
  WorldGuard: false
# === [ World Related Settings ] ===
Worlds:
  # Enable world based restrictions
  Restrict: false
  Enabled Worlds:
  - world
  - world2
Modding:
  Disable Durability Fix: false
Debug: none
# The config version for update checks
Version: 7.014699935913086
# === [ bStats Metrics Settings ] ===
bStats:
  # Should we send stats at all? Please keep this in so we have an overview of spread of versions <3
  Active: true
  # This setting sends a bit more detailed information about which features are used at all. Thank you for supporting me!
  Full: true```

**Comment by slipcor** [comment]
OH won't you look at this. I actually fixed the config commenting, and I will not remove any feature for now. You and the motto "don't change a running system" have convinced me :D

After all, I would have only removed something if absolutely no-one would be using it. And also, it would have to be a feature that causes a lot of trouble. I do not think there is a lot of trouble at the moment ;)

**Comment by VL4DST3R** [comment]
Indeed! I couldn't have asked for more! Thank you!
