### ISSUE TITLE
Paper server flooding errors and lagging heavily when breaking trees

### ISSUE THREAD

**Issue by VL4DST3R** [slipcor/TreeAssist#67]
Started noticing this error after updating to the latest version:

```
22:28:40 [SEVERE] ------------------------------
22:28:44 [SEVERE] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-467 (MC: 1.16.5) ---
22:28:44 [SEVERE] The server has not responded for 15 seconds! Creating thread dump
22:28:44 [SEVERE] ------------------------------
22:28:44 [SEVERE] Server thread dump (Look for plugins here before reporting to Paper!):
22:28:44 [SEVERE] ------------------------------
22:28:44 [SEVERE] Current Thread: Server thread
22:28:44 [SEVERE] 	PID: 55 | Suspended: false | Native: false | State: RUNNABLE
22:28:44 [SEVERE] 	Stack:
22:28:44 [SEVERE] 		java.base/java.util.HashMap.putVal(HashMap.java:626)
22:28:44 [SEVERE] 		java.base/java.util.HashMap.put(HashMap.java:607)
22:28:44 [SEVERE] 		java.base/java.util.HashSet.add(HashSet.java:220)
22:28:44 [SEVERE] 		java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:352)
22:28:44 [SEVERE] 		java.base/java.util.LinkedHashSet.<init>(LinkedHashSet.java:169)
22:28:44 [SEVERE] 		net.slipcor.treeassist.core.TreeStructure.<init>(TreeStructure.java:106)
22:28:44 [SEVERE] 		net.slipcor.treeassist.listeners.TreeAssistBlockListener.onBlockBreak(TreeAssistBlockListener.java:241)
22:28:44 [SEVERE] 		com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor486.execute(Unknown Source)
22:28:44 [SEVERE] 		org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
22:28:44 [SEVERE] 		org.bukkit.plugin.EventExecutor$$Lambda$4317/000000000000000000.execute(Unknown Source)
22:28:44 [SEVERE] 		co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
22:28:44 [SEVERE] 		org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
22:28:44 [SEVERE] 		org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:283)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:249)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1485)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$5902/000000000000000000.run(Unknown Source)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
22:28:45 [SEVERE] 		net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3149/000000000000000000.run(Unknown Source)
22:28:45 [SEVERE] 		java.base/java.lang.Thread.run(Thread.java:836)
22:28:45 [SEVERE] ------------------------------
22:28:45 [SEVERE] --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
22:28:45 [SEVERE] ------------------------------
```

Causes the server to lag terribly and rubber-band when breaking blocks. This wasn't an issue on the previous version, before you started to remove functionality from the mod.

**Comment by slipcor** [comment]
Please be more specific about the exact version you are using now and you have been using before. Which functionality do you speak of?

**Comment by VL4DST3R** [comment]
v7.0.148 is what i updated to, when the issue started happening.

I mentioned you removing features as a frame of reference. If you remember, we discussed this a while back when you made your "Happy holidays!" update on spigotmc. There, you were discussing about removing unused features and i asked you to kindly not remove them just for the sake of removing, as the customization of this plugin is what made it great.

After posting this i went ahead and updated to the current latest, v7.1.2 and the issue seems to now be fixed. I also noticed the ticket before mine seems to be about the same issue, and you addressed it in an update, so i think it's safe to say you can close this ticket as well as you've fixed it already.

**Comment by slipcor** [comment]
Alright, first off, I am happy that the version you are using right now seems to run more stable 👍 

Secondly I would ask you to reconsider using "latest" as a indicator of the version, as the actual latest version you get right now (and it has been like this for a long time) varies depending on where you check (bukkit, spigot, discord) and which version you look for (alpha, beta, release, anything in between). I understand that I can do better about releasing builds, and I am planning to streamline this process and synchronize the builds facing outwards.

About the other ticket, I am not sure if this is because you only took a part of the full crashlog, but what I see does not relate to the "fix" I did for the crash. I have a feeling that this needs further investigation because what I did might just have coincidental benefits and the underlying problem might still be there.

Would you be up for joining my discord and opening a ticket so we can debug what is going on? I sadly do not have a server with active player on it to test these things in a live environment.

Feel free to close this ticket again if the answer is no ^^

**Comment by VL4DST3R** [comment]
> varies depending on where you check (bukkit, spigot, discord)

Shouldn't this be the same across the board? Sounds like a great way to cause confusion if it is not...

As for further testing, i have a small private server with about 6-8 players on most of the daytime here where we live. While not too keen on joining even more servers at the moment, I have nothing against helping you with this further if it is really needed, but as far as i am aware, after updating to 7.1.2 the issue now seems completely fixed. 

I even tested it in your favorite biome: the jungle ^_^ and it worked as expected, that's why i closed the ticket. 

If i'm missing something do let me know.

**Comment by slipcor** [comment]
Yes. Ideally the versions should all be the same, but I want a fast track pipeline for bleeding edge builds for people who have crash issues and specific setups that might cause more problems. Generally speaking, the plugin runs smoothly, with hundreds of servers and only a few people reported crashes, for this plugin, a total of two people.

I can only hope that the rest is fine and not just "dealing with crashes". Crashes are the worst which is why I take this very seriously and am glad that you reported back that the crashes have stopped 👍 

Anyway, bukkit has a relatively strict release system (alpha, beta, release) that I am trying - admittedly in a bad way - to adhere to and I am always mindful about uploading there as there have been some issues lately with delays and builds getting rejected for invalid reasons.

Anyhow, discord is the best way for me to release latest dev builds, as the CI has died and the person who runs it is unavailable.

Coming back to your issue, you know best if it works or not. I understand the downsides of being in many discord servers, believe me. If your server runs fine now, then probably I also fixed the crash for you.

Let's wait some days of live testing to verify this. Keeping my fingers crossed.

Thanks for the jungle reminder, it has been a struggle lately, so I am glad it is still doing well :D

**Comment by VL4DST3R** [comment]
Glad to hear you take it this so seriously, its rarely to see such a dev for a free plugin! And your track record indeed proves this, thank you for this!

If you need a server like mine to test stuff on - do tell me and i'll gladly help you or give you access to it.

Yes, ill obviously keep testing it as we continue playing, but given the drastic difference it caused already i'm pretty confident its properly fixed now!

**Comment by slipcor** [comment]
I am happy that this works now :) I will consider contacting you for tests <3
