### ISSUE TITLE
[Feature Request] Togglable noReplant

### ISSUE THREAD

**Issue by tawAsh1** [slipcor/TreeAssist#71]
Hello!

I would like to propose a toggleable replant control feature.

**command idea**
`/treeassist replant true `
-> replant will be performed
`/treeassist replant false`
-> replant will not be performed

This command conflicts with the existing `noreplant` command, but I think it would be nice to override the `noreplant` setting. 

As an additional task, it might be nice to be able to keep the configuration state of each player in a file or something.

I would like to create a PR if this idea looks good. 
Please let me know if you have any suggestions.

**Comment by slipcor** [comment]
So you mean that where the "noreplant" currently only ever restricts you want the specific opposite, which basically hooks into the same logic as the "replanting -> enforce" but toggle-able so you can "enforce sapling replant" for a limited time (until you disable it)

I would be happy to review a PR! 

You should be able to trace down where this setting would need to be checked by looking for the enforce-config setting and where it is checked.

I am absolutely ok with duplicating whatever the logic was to check "noreplant" for the opposite logic. Because this "replant" thing will always enforce this globally - or user based, however you make this happen. I.e. I am not concerned about overhead by adding another management set, hashmap or whatever you do 👍 

If you want to allow this for individual users, too I'd suggest the logic as follows

```/ta replant SLiPCoR - toggle SLiPCoR's replanting enforcement
/ta replant SLiPCoR true - set replanting enforcement for SLiPCoR
/ta replant - toggle your replanting enforcement
/ta replant true - activate your replanting enforcement
/ta replant global - toggle enforcing for everyone
/ta replant global false - disable [temporary] enforcement```

This would require distinct permissions, for "yourself", for "other" and for "global" :)

Changes to this logic are welcome and I will consider what you throw at me. The more versatile the solution, the higher the chances of me pulling it :)

Thank you for your time.
