### ISSUE TITLE
Make semifloating trees valid

### ISSUE THREAD

**Issue by molor** [slipcor/TreeAssist#76]
Moved from https://github.com/slipcor/TreeAssist/issues/75#issuecomment-867896869 to fix problems like this.

![image](https://user-images.githubusercontent.com/19989717/123322890-79e98300-d53d-11eb-91cf-aa425c560564.png)

**Comment by slipcor** [comment]
short comment here: this applies to all tree types, they can randomly generate in mid air, I have seen 2 blocks distance so far, can be water and air.

This needs a hackfix, but only for "the main tree" and not "when finding neighbors"

I think I have an idea where to hook into:

https://github.com/slipcor/TreeAssist/blob/master/src/main/java/net/slipcor/treeassist/discovery/TreeStructure.java#L104

This needs to support air. Globally and generally, but only if "onlyTrunk" is false, that is the case when we find "the main" tree that we are currently cutting down.

**Comment by slipcor** [comment]
Okay I will try my luck again another day. Today's results have not been great. I tried allowing a gap of 2 blocks below the trunk. This lead to two different issues with regular trees that work normally currently:

1) Dark Oak trees that are next to a hill think they have more than 4 trunks, because branches that hang low will be considered "having a gap" , and I regularly get false positive results like "found 6 trunks" and this leads to a failure. Trying to override might still cause trouble as some of these trunks will be actually invalid because they do not go all the way up, and/or they might not have enough leaves where they end (this is a critical error in tree determination)

2) Really tall jungle trees sometimes only remove 1/4 of their trunks, I think they are not recognized as "thick trees" any more. The reason for this is unclear to me.

**Comment by slipcor** [comment]
This is too much of a clash with my current logic. It seems not compatible. I am sorry :(
