### ISSUE TITLE
Request: AureliumSkills compatibility

### ISSUE THREAD

**Issue by justapedro** [slipcor/TreeAssist#79]
Just like McMMO, having AureliumSkills compatibillity would be a nice adittion

Plugin link: https://www.spigotmc.org/resources/aurelium-skills-advanced-skills-stats-abilities-and-more.81069/

**Comment by slipcor** [comment]
Alright, I am in the process of implementing this. So, their API requires me to specify an amount of EXP to add. You'd need a configuration for that, right? Would this need a different amount then for each wood type?

Or would it just be "1.0" per block or per tree, depending a setting like we have for mcMMO?

Because right now that is all I give mcMMO, I tell it "a player broke a LOG" and mcMMO handles the rest.

**Comment by slipcor** [comment]
Let's hope that it works now, I added a few config settings to v7.3.23 - you can set the EXP amount per block, or per tree broken by the plugin for the player :)
