### ISSUE TITLE
It's a giant Mushroom! MAYBE IT'S FRIENDLY

### ISSUE THREAD

**Issue by WildFyr16** [slipcor/TreeAssist#91]
The chopping mechanic seems to work on Brown Giant Mushrooms but nor Red. Moreover, when chopping down a Brown Mushroom, it drops apples.

**Comment by slipcor** [comment]
Hmm this is the first time I hear from this issue, can you verify that your files are somewhat in order, in the way they are here?

https://github.com/slipcor/TreeAssist/tree/master/src/main/resources/trees

There should be a mushroom.yml in the root folder that has a parent set to default
https://github.com/slipcor/TreeAssist/blob/master/src/main/resources/trees/mushroom.yml#L27

And I did a test some time ago, and even though the default has the drops set to default to apples:
https://github.com/slipcor/TreeAssist/blob/master/src/main/resources/trees/default.yml#L77

I have not seen this happen really... however I might have been lucky because the chance is 1 in 100

Can you try copying over the apple values from default to mushroom and setting them to 0 ? So that the chance inside mushroom.yml is 0 for apples?

**Comment by WildFyr16** [comment]
After looking in the Mushroom.yml I believe I found the issue for the red mushroom. Minimum Height was set to 5, the red mushrooms I was trying to chop were only 4 blocks tall (Short stubby ones). Lowering this *should* fix the issue, and after chopping a red mushroom that was taller than 5 blocks, it worked fine.

As for the drops, the only defined custom drop is minecraft:mushroom_stem. So I did what you said and copied over the apple and golden apple chances and set them both to 0. If the issue persists, I will let you know.
